(* DO NOT EDIT THIS FILE: automatically generated by ../configure *)
(* Exact command that generated this file: *)
(* ./configure.ml -prefix /Users/erutuf/Documents/prosym20/jscoq//_build/install/jscoq+32bit -native-compiler no -bytecode-compiler no -coqide no *)

let local = false
let coqlib = "/Users/erutuf/Documents/prosym20/jscoq//_build/install/jscoq+32bit/lib/coq"
let configdir = "/Users/erutuf/Documents/prosym20/jscoq//_build/install/jscoq+32bit/etc/xdg/coq"
let datadir = "/Users/erutuf/Documents/prosym20/jscoq//_build/install/jscoq+32bit/share/coq"
let docdir = "/Users/erutuf/Documents/prosym20/jscoq//_build/install/jscoq+32bit/share/doc/coq"
let coqlibsuffix = "lib/coq"
let configdirsuffix = "etc/xdg/coq"
let datadirsuffix = "share/coq"
let docdirsuffix = "share/doc/coq"
let ocamlfind = "/Users/erutuf/.opam/jscoq+32bit/bin/ocamlfind"
let caml_flags = "-thread -rectypes -w +a-4-9-27-41-42-44-45-48-58   -safe-string -strict-sequence"
let version = "8.10.2"
let caml_version = "4.07.1"
let caml_version_nums = [4;7;1]
let date = "January 2020"
let compile_date = "Jan 5 2020 14:29:21"
let arch = "Darwin"
let arch_is_win32 = false
let exec_extension = ""
let gtk_platform = `X11
let has_natdynlink = true
let vo_magic_number = 81000
let state_magic_number = 581000
let browser = "open %s"
let wwwcoq = "http://coq.inria.fr/"
let wwwbugtracker = "http://coq.inria.fr/bugs/"
let wwwrefman = "http://coq.inria.fr/distrib/V8.10.2/refman/"
let wwwstdlib = "http://coq.inria.fr/distrib/V8.10.2/stdlib/"
let localwwwrefman = "file://Users/erutuf/Documents/prosym20/jscoq//_build/install/jscoq+32bit/share/doc/coq/html/refman"
let bytecode_compiler = false
let native_compiler = false

let core_src_dirs = [
  "config";
  "lib";
  "clib";
  "kernel";
  "library";
  "engine";
  "pretyping";
  "interp";
  "gramlib";
  "gramlib/.pack";
  "parsing";
  "proofs";
  "tactics";
  "toplevel";
  "printing";
  "ide";
  "stm";
  "vernac";
]

let plugins_dirs = [
  "plugins/btauto";
  "plugins/cc";
  "plugins/derive";
  "plugins/extraction";
  "plugins/firstorder";
  "plugins/fourier";
  "plugins/funind";
  "plugins/ltac";
  "plugins/micromega";
  "plugins/nsatz";
  "plugins/omega";
  "plugins/rtauto";
  "plugins/setoid_ring";
  "plugins/ssr";
  "plugins/ssrmatching";
  "plugins/syntax";
]

let all_src_dirs = core_src_dirs @ plugins_dirs
